/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gorunum;

import Kisi.Doktor;
import Kisi.DoktorDurum;
import Servis.Poliklinik;
import VeriTabani.Veritabani;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author oktay
 */
public class DoktorRandevu extends javax.swing.JFrame {

    List<Poliklinik> listPoli=new ArrayList<>();
    List<Doktor> listToktor=new ArrayList<>();
    List<DoktorDurum> listDoktorDurum;
    
    public static Poliklinik seciliPoliklinik;
    public  static DoktorDurum seciliDoktorDurum;
    public static Doktor seciliDoktor;
    public DoktorRandevu() {
        initComponents();
        listPoli= Veritabani.readObject(new Poliklinik());
        
        jCombopoli.removeAllItems();
       
        for(Poliklinik p:listPoli){
            jCombopoli.addItem(p);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxToktor = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jCombopoli = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBoxToktor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxToktor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxToktorActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jCombopoli.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCombopoli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCombopoliMouseClicked(evt);
            }
        });
        jCombopoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombopoliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCombopoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jComboBoxToktor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxToktor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombopoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCombopoliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCombopoliMouseClicked
       
    }//GEN-LAST:event_jCombopoliMouseClicked

    private void jCombopoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombopoliActionPerformed
        seciliPoliklinik=(Poliklinik)jCombopoli.getSelectedItem();
       
       if(seciliPoliklinik==null){
           System.out.println("nuuuul");
           return;
       }
       
       listToktor=Veritabani.readObject(new Doktor());
       jComboBoxToktor.removeAllItems();
       for(Doktor d:listToktor){
           if(seciliPoliklinik.getId()==d.getPoliklinik().getId()){
               jComboBoxToktor.addItem(d);
           }
       }
    }//GEN-LAST:event_jCombopoliActionPerformed

    private void jComboBoxToktorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxToktorActionPerformed
       seciliDoktor=(Doktor)jComboBoxToktor.getSelectedItem();
       
       if(seciliDoktor==null){
           return;
       }
       DefaultListModel dlm=new DefaultListModel<>();
       jList1.setModel(dlm);
       jList1.removeAll();
       listDoktorDurum=Veritabani.readObject(new DoktorDurum());
       
       for(DoktorDurum dd:listDoktorDurum){
           if(seciliDoktor.getId()==dd.getDoktor().getId()){
               System.out.println(" Dok  "+dd.getDoktor()
                   +" hasta  "+dd.getHasta()+
                   " polii  "+dd.getPoliklinik());
               
               
               dlm.addElement("Poli "+dd.getPoliklinik()+
                       "  Hasta  "+dd.getHasta()+
                       "  Zaman "+dd.getTarih());
           }
       }
    }//GEN-LAST:event_jComboBoxToktorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoktorRandevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoktorRandevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoktorRandevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoktorRandevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoktorRandevu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxToktor;
    private javax.swing.JComboBox jCombopoli;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
