/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Hasta_Kabul.java
 *
 * Created on 09.May.2013, 19:48:50
 */
package gorunum;

import Kisi.Doktor;
import Kisi.DoktorDurum;
import Kisi.Hasta;
import Servis.Izin;

import Servis.Poliklinik;
import Servis.Ucret;
import VeriTabani.Veritabani;

import java.text.DateFormatSymbols;

import java.util.ArrayList;


import java.util.List;
import java.util.Locale;

/**
 *
 * @author oktay
 */
public final class Vezne_Hasta_Kabul extends javax.swing.JFrame {

    List<Poliklinik> polikliniks = new ArrayList<>();
    List<Doktor> doktors = new ArrayList<>();
    public  static Poliklinik seciliPoliklinik;
    public static Doktor seciliDoktor;
    List<DoktorDurum> doktorDurumList=new ArrayList<>();
    List<String> saatList = new ArrayList<>();
    
    List<Hasta> hastaList= new ArrayList<>();
    
    Hasta seciliHasta;
    
    String seciliTarih;
    
     List<Izin> izinList;
     

    /**
     * Creates new form Hasta_Kabul
     */
    public Vezne_Hasta_Kabul() {
        initComponents();
        
        hastaList=Veritabani.readObject(new Hasta());
        
        jComboAd.removeAllItems();
        
        for(Hasta h:hastaList){
            jComboAd.addItem(h);
        }

       tarihEkle();
        System.out.println("zaman ");
        polikliniks = (List<Poliklinik>) Veritabani.readObject(new Poliklinik());
        saatCombo.removeAllItems();

        for (int saat = 9; saat < 17; saat++) {
            if (saat == 12) {
                continue;
            }
            for (int dakka = 0; dakka < 12; dakka++) {
                String saatStr = String.format("%02d:%02d", saat, dakka * 5);
                saatList.add(saatStr);
            }

        }

       

        jComboPoli.removeAllItems();

        for (Poliklinik p : polikliniks) {
            jComboPoli.addItem(p);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField_Tc = new javax.swing.JTextField();
        jComboAd = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboPoli = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboDoktor = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        saatCombo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        gun = new javax.swing.JComboBox();
        ay = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ddKAydet = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelpara = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelyansimis = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_sifirla = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(211, 228, 226));

        jLabel1.setText("TC Kimlik No:");

        jLabel2.setText("Hasta Adı:");

        jLabel4.setText("Sağlık Güvencesi Tipi:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SSK", "BAGKUR", "EMEKLİ SANDIGI", "DİGER", " " }));

        jComboAd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Tc)
                            .addComponent(jComboAd, 0, 147, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jPanel4.setBackground(new java.awt.Color(211, 228, 226));
        jPanel4.setPreferredSize(new java.awt.Dimension(395, 359));

        jLabel5.setText("Poliklinik Adı:");

        jComboPoli.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboPoli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboPoliMouseClicked(evt);
            }
        });
        jComboPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPoliActionPerformed(evt);
            }
        });

        jLabel6.setText("Doktor Adı:");

        jComboDoktor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboDoktor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboDoktorActionPerformed(evt);
            }
        });

        jLabel7.setText("Tarih:");

        jLabel8.setText("Saat:");

        jLabel12.setText("Açıklama:");
        jLabel12.setToolTipText("");

        saatCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        saatCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saatComboMouseClicked(evt);
            }
        });
        saatCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saatComboActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jEditorPane1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        gun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ayMouseClicked(evt);
            }
        });
        ay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8)
                        .addGap(71, 71, 71)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(336, 336, 336))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboPoli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboDoktor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(89, 89, 89)
                                .addComponent(gun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(ay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboPoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboDoktor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(gun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(saatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        jLabel9.setText("HASTA KABUL SAYFASI");

        jLabel10.setText("HASTA BİLGİLERİ");

        jLabel11.setText("RANDEVU BİLGİLERİ");

        ddKAydet.setText("KAYDET");
        ddKAydet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ddKAydetMouseClicked(evt);
            }
        });
        ddKAydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddKAydetActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(211, 228, 226));

        jLabel3.setText("Tutar :");

        jLabelpara.setText("jLabel14");

        jLabel14.setText("Yansımış Tutar");

        jLabelyansimis.setText("jLabel15");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel3))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelpara)
                    .addComponent(jLabelyansimis))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelpara))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabelyansimis))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabel13.setText("ÜCRET BİLGİLERİ");

        btn_sifirla.setText("Sıfırla");
        btn_sifirla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sifirlaActionPerformed(evt);
            }
        });

        jButton1.setText("Yeni Hasta");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 1020, Short.MAX_VALUE)
                        .addComponent(ddKAydet, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(368, 368, 368)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(btn_sifirla))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13))
                                        .addGap(164, 164, 164)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 419, Short.MAX_VALUE)))))
                        .addGap(28, 28, 28)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel10)
                .addGap(357, 357, 357)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(ddKAydet))
                    .addComponent(btn_sifirla))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void ddKAydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddKAydetActionPerformed
        System.out.println("jButton1ActionPerformed");
        
    }//GEN-LAST:event_ddKAydetActionPerformed

private void btn_sifirlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sifirlaActionPerformed
}//GEN-LAST:event_btn_sifirlaActionPerformed

    private void ddKAydetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ddKAydetMouseClicked

        seciliPoliklinik = (Poliklinik) jComboPoli.getSelectedItem();
        seciliDoktor = (Doktor) jComboDoktor.getSelectedItem();
        seciliHasta=(Hasta)jComboAd.getSelectedItem();
        DoktorDurum dd = new DoktorDurum();
        dd.setDoktor(seciliDoktor);
        dd.setPoliklinik(seciliPoliklinik);

        seciliHasta.setAd(seciliHasta.getKisi().getAd());
        seciliHasta.setAciklama(jTextArea1.getText().toString());
        seciliHasta.setSaat(saatCombo.getSelectedItem().toString());
        seciliHasta.setTarih(seciliTarih);
        seciliHasta.setPoliklinik(seciliPoliklinik);
        seciliHasta.getKisi().setSSN((String)jComboBox1.getSelectedItem());
        dd.setSaat(saatCombo.getSelectedItem().toString());
      
        seciliHasta.addDoktor(seciliDoktor);
        seciliDoktor.addHasta(seciliHasta);
        dd.setTarih((String)gun.getSelectedItem()+(String)ay.getSelectedItem());
        dd.setHasta(seciliHasta);
        seciliDoktor.addDurum(dd);
        
        
        Veritabani.persist(dd);
        Veritabani.merge(seciliHasta);
        Veritabani.merge(seciliDoktor);
        Veritabani.merge(seciliPoliklinik);
        /* System.out.println("Doktor durum"+dd.getDoktor().getKisi().getAd());
         System.out.println("Doktor durum"+dd.getDoktor().getPoliklinik().getAd());
         System.out.println("Doktor durum"+dd.getHasta().getKisi().getAd());*/


    }//GEN-LAST:event_ddKAydetMouseClicked

    private void saatComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saatComboActionPerformed

    }//GEN-LAST:event_saatComboActionPerformed

    private void saatComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saatComboMouseClicked

    }//GEN-LAST:event_saatComboMouseClicked

    private void jComboDoktorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboDoktorActionPerformed
      seciliDoktor=(Doktor)jComboDoktor.getSelectedItem();
         if(seciliDoktor==null){
            return;
        }
        System.out.println(""+seciliDoktor.getKisi().getAd());
       
   
    }//GEN-LAST:event_jComboDoktorActionPerformed

    private void jComboPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPoliActionPerformed
        seciliPoliklinik = (Poliklinik) jComboPoli.getSelectedItem();

        if (seciliPoliklinik == null) {
            return;
        }

        jComboDoktor.removeAllItems();
        doktors = (List<Doktor>) Veritabani.readObject(new Doktor());
        for (Doktor d : doktors) {
            if (d.getPoliklinik().getId() == seciliPoliklinik.getId()) {
                jComboDoktor.addItem(d);
            }

        }
    }//GEN-LAST:event_jComboPoliActionPerformed

    private void jComboPoliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboPoliMouseClicked
  
      
    }//GEN-LAST:event_jComboPoliMouseClicked

    private void ayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayActionPerformed
     
      seciliTarih=(String)gun.getSelectedItem()+(String)ay.getSelectedItem();
      if(seciliTarih==null | seciliDoktor==null){
          return;
      }
      
      List<String> strList=new ArrayList<>();
      izinList= Veritabani.readObject(new Izin());
      for(Izin izin:izinList){
          strList.add(""+izin.getGun()+izin.getAy());
      }
      
      if(strList.contains(seciliTarih)){
          System.out.println("burdradradrdradradrda");
          Uyari uyari=new Uyari();
          uyari.setUyariString("Doktor Bu tarihte İzinli");
          uyari.setVisible(true);
          tarihEkle();
      }
      System.out.println("doktoo  "+seciliDoktor.getKisi().getAd());
      
      System.out.println("ra"+seciliTarih);
      
      doktorDurumList=Veritabani.readObject(new DoktorDurum());
              for(DoktorDurum dd:doktorDurumList){
                  if(seciliDoktor.getId()==dd.getDoktor().getId() && dd.getTarih().equals(seciliTarih)){
                      saatList.remove(dd.getSaat());
                  }
              }
       saatCombo.removeAllItems();
      for(String s:saatList){
          saatCombo.addItem(s);
      }
    }//GEN-LAST:event_ayActionPerformed

    private void ayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayMouseClicked
          
   
    }//GEN-LAST:event_ayMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        YeniHasta yeniHasta= new YeniHasta();
        yeniHasta.setTitle("Yeni Hasta Ekleyiver");
        yeniHasta.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jComboAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAdActionPerformed
            seciliHasta=(Hasta)jComboAd.getSelectedItem();
            if(seciliHasta!=null){
                jTextField_Tc.setText(seciliHasta.getKisi().getTc_kimlik());
                if(seciliHasta.getUcret()!=null){
                     jLabelpara.setText(""+seciliHasta.getUcret().getUcretTutar());
                     jLabelyansimis.setText(""+seciliHasta.getUcret().getYansimisTutar());
                }
                else{
                     jLabelpara.setText("0");
                }
            }
    }//GEN-LAST:event_jComboAdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hasta_Kabul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hasta_Kabul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hasta_Kabul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hasta_Kabul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vezne_Hasta_Kabul().setVisible(true);

            }
        });
       
        

    }
    
   public void tarihEkle(){
        String[] aylar= new DateFormatSymbols(Locale.getDefault()).getMonths();
        
        ay.removeAllItems();
        
        for(String s:aylar){
            ay.addItem(s);
        }
        
        gun.removeAllItems();
        
        for(int i=0;i<31;i++){
            gun.addItem(""+i );
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ay;
    private javax.swing.JButton btn_sifirla;
    private javax.swing.JButton ddKAydet;
    private javax.swing.JComboBox gun;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboAd;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboDoktor;
    private javax.swing.JComboBox jComboPoli;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelpara;
    private javax.swing.JLabel jLabelyansimis;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField_Tc;
    private javax.swing.JComboBox saatCombo;
    // End of variables declaration//GEN-END:variables

    private static class Hasta_Kabul {

        public Hasta_Kabul() {
        }
    }
}
